doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        host: '%env(DB_HOST)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        dbname: '%env(DB_NAME)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                extract: DoctrineExtensions\Query\Postgresql\ExtractFunction
                greatest: DoctrineExtensions\Query\Postgresql\Greatest
            numeric_functions:
                least: DoctrineExtensions\Query\Postgresql\Least
                greatest: DoctrineExtensions\Query\Postgresql\Greatest
            string_functions:
                greatest: DoctrineExtensions\Query\Postgresql\Greatest
