# docker-compose.yml
version: '2'

services:
    db:
        image: postgres:9.6
        restart: always
        volumes:
            - ${STORAGE_PATH}/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    app:
        image: ${APP_IMAGE}
        restart: always
        env_file:
          - .env
        volumes:
            - ./docker/php/www.${ENVIRONMENT}.conf:/etc/php/7.4/fpm/pool.d/www.conf.env:ro
            - ./docker/php/conf.d/20-xdebug.${ENVIRONMENT}.ini:/etc/php/7.4/fpm/conf.d/20-xdebug.ini:ro
            - ./docker/empty.env:/var/app/.env
            - ${STORAGE_PATH}/documents:/var/app/public/documents
            - ${STORAGE_PATH}/config/jwt:/var/app/config/jwt
            - ${STORAGE_PATH}/upload:/var/upload
        environment:
            DB_HOST: db
            APP_DEBUG: 0
        links:
            - db

    nginx:
        image: nginx:1.19
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        restart: always
        entrypoint: '/var/www/entrypoint.sh'
        command: 'nginx -g "daemon off;"'
        environment:
            DOCKER_USER: 'www-data'
            DOCKER_GROUP: 'www-data'
            LOCAL_USER_ID: ${UUID}
            LOCAL_GROUP_ID: ${GGID}
            WORDPRESS_HOST: ${WORDPRESS_HOST}
            WORDPRESS_PORT: ${WORDPRESS_PORT}
            FILE_MAX_SIZE: ${FILE_MAX_SIZE}
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/conf.d/site.${ENVIRONMENT}.conf:/etc/nginx/conf.d.env/default.conf:ro
            - ./docker/nginx/conf.d/htpasswd.wordpress:/etc/nginx/conf.d/htpasswd.wordpress:ro
            - ./docker/nginx/entrypoint:/var/www
        volumes_from:
            - app
        links:
            - app