api_projects_users_create:
  path: /
  defaults: { _controller: 'App\Controller\Api\Project\AssignedUsersController::create' }
  methods: [ 'PUT' ]

api_projects_users_get_all:
  path: /
  defaults: { _controller: 'App\Controller\Api\Project\AssignedUsersController::getAll' }
  methods: [ 'GET' ]

api_projects_users_delete:
  path: /{user}
  defaults: { _controller: 'App\Controller\Api\Project\AssignedUsersController::delete' }
  methods: [ 'DELETE' ]
  requirements:
    user: "[0-9]+"

api_projects_users_update:
  path: /{user}
  defaults: { _controller: 'App\Controller\Api\Project\AssignedUsersController::update' }
  methods: [ 'PATCH' ]
  requirements:
    user: "[0-9]+"
