api_auth_login:
  path: /login

api_auth_refresh_token:
  path:     /refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_auth_register:
  path: /register
  defaults: { _controller: 'App\Controller\Api\UserController::create' }
  methods: [ 'POST' ]