api_auth:
  resource: auth.yaml
  prefix: /auth

api_users:
  resource: users/users.yaml
  prefix: /users

api_projects:
  resource: projects/projects.yaml
  prefix: /projects

api_timezones:
  resource: timezones.yaml
  prefix: /timezones