api_users_timer_start:
  path: /
  defaults: { _controller: 'App\Controller\Api\User\TimerController::start' }
  methods: [ 'PUT' ]

api_users_timer_stop:
  path: /stop
  defaults: { _controller: 'App\Controller\Api\User\TimerController::stop' }
  methods: [ 'POST' ]